import configparser
config = configparser.ConfigParser()

config.add_section('IT')
#config.set('IT', 'GENERAL SETTINGS', '')
config.set('IT', 'Name', 'IT_Network' )
config.set('IT', 'RAM', '512MB')
config.set('IT', 'vCPUs', '1')
config.set('IT', 'Qemu binary', '/usr/bin/qemu-system-x86-64(v4.2.1)')
config.set('IT', 'Boot priority', 'CD/DVD-ROM or HDD')
config.set('IT', 'On close', 'Power off the VM')
config.set('IT', 'Console type', 'telnet')
#config.set('IT', 'NETWORK', '')
config.set('IT', 'Adapters', '13')
config.set('IT', 'Base MAC', '0c:1c:b2:85:00:00')
config.set('IT', 'Type', 'Realtek 8139 Ethernet (rtl8139)')
config.set('IT', 'Replicate network connection states in Qemu', 'Yes')
config.add_sec', 'Name', 'MGMT_Network' )

config.set('MGMT', 'RAM', '512MB')
config.set('MGMT', 'vCPUs', '1')
config.set('MGMT', 'Qemu binary', '/usr/bin/qemu-system-x86-64(v4.2.1)')
config.set('MGMT', 'Boot priority', 'CD/DVD-ROM or HDD')
config.set('MGMT', 'On close', 'Power off the VM')
config.set('MGMT', 'Console type', 'telnet')
#config.set('MGMT', 'Network', '')
config.set('MGMT', 'Adapters', '13')
config.set('MGMT', 'Base MAC', '0c:cc:78:5d:00:00')
config.set('MGMT', 'Type', 'Realtek 8139 Ethernet (rtl8139)')
config.set('MGMT', 'Replicate network connection states in Qemu', 'Yes')

config.add_section('ACCT')
#config.set('ACCT', 'GENERAL SETTINGS', '')
config.set('ACCT', 'Name', 'ACCT_Network' )
config.set('ACCT', 'RAM', '512MB')
config.set('ACCT', 'vCPUs', '1')
config.set('ACCT', 'Qemu binary', '/usr/bin/qemu-system-x86-64(v4.2.1)')
config.set('ACCT', 'Boot priority', 'CD/DVD-ROM or HDD')
config.set('ACCT', 'On close', 'Power off the VM')
config.set('ACCT', 'Console type', 'telnet')
#config.set('ACCT', 'NETWORK', '')
config.set('ACCT', 'Adapters', '13')
config.set('ACCT',tion('MGMT')
#config.set('MGMT', 'General settings', '')
config.set('MGMT 'Base MAC', '0c:40:34:07:00:00')
config.set('ACCT', 'Type', 'Realtek 8139 Ethernet (rtl8139)')
config.set('ACCT', 'Replicate network connection states in Qemu', 'Yes')

config.add_section('USER')
#config.set('USER', 'GENERAL SETTINGS', '')
config.set('USER', 'Name', 'USER_Network' )
config.set('USER', 'RAM', '512MB')
config.set('USER', 'vCPUs', '1')
config.set('USER', 'Qemu binary', '/usr/bin/qemu-system-x86-64(v4.2.1)')
config.set('USER', 'Boot priority', 'CD/DVD-ROM or HDD')
config.set('USER', 'On close', 'Power off the VM')
config.set('USER', 'Console type', 'telnet')
#config.set('USER', 'NETWORK', '')
config.set('USER', 'Adapters', '13')
config.set('USER', 'Base MAC', '0c:e0:f2:0b:00:00')
config.set('USER', 'Type', 'Realtek 8139 Ethernet (rtl8139)')
config.set('USER', 'Replicate network connection states in Qemu', 'Yes')

with open('Task_B_python.ini', 'w') as f:
	config.write(f)
	
	
	 
